<?php
/**
 *
 * Created by PhpStorm.
 * User: Roy Freij - Netcreaties
 * Date: 11-5-2017
 * Time: 12:55
 */

/*
 * Do not edit this file
 */
session_start();

ini_set('display_errors',1);
ini_set('display_startup_errors',1);
error_reporting(-1);

require_once( 'app/services/AutoLoader.php' );

use \app\services\Autoloader;
use \app\ServiceLoader;
use \app\services\Database;
use \app\services\Router;
use \app\services\Message;
use \app\services\Authenticate;

new Autoloader();

$load = new ServiceLoader();

$load->set( 'Database', new Database(), true );
$load->set( 'Message', new Message(), true );
$load->set( 'Authenticate', new Authenticate(), true );

$router = new Router( $load );

require('web/routes.php');

$router->dispatch();

/*
 * Do not edit this file
 */
